# Generated by Django 5.0.4 on 2024-08-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='mp3_file',
            field=models.FileField(upload_to='upload/mp3_files/'),
        ),
    ]
