# Generated by Django 5.0.4 on 2024-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_audiofile_mp3_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='mp3_file',
            field=models.FileField(upload_to='upload/covert_mp3_to_mp4/files'),
        ),
    ]
