# Generated by Django 5.0.4 on 2024-08-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_audiofile_mp3_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='mp4_file',
            field=models.FileField(blank=True, null=True, upload_to='upload/static/covert_mp3_to_mp4/files'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='mp3_file',
            field=models.FileField(upload_to='upload/static/covert_mp3_to_mp4/files'),
        ),
    ]
